# Generated by Django 3.2.4 on 2021-07-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='dfghj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
